//Question 1. Declare a variable called age & assign to it your age. Show your age in an alert box.
let age = 15;
alert("I am "+ age + "" + "years old.")
//Question 2. Declare & initialize a variable to keep track of how many
//times a visitor has visited a web page. Show his/her
//number of visits on your web page. For example: “You
//have visited this site N times”.
let numberOfVisit = 14;
alert("you have visited this site " + numberOfVisit + "times.")
//Question 3. Declare a variable called birthYear & assign to it your
//birth year. Show the following message in your browser:
let birthYear = 1990;
document.write("My birthday year is" + birthYear + "<br>");
document.write("Data type of declared is number");
//Question 4. A visitor visits an online clothing store
//www.xyzClothing.com . Write a script to store in variables
//the following information:
//a. Visitor’s name
//b. Product title
//c. Quantity i.e. how many products a visitor wants to order
//Show the following message in your browser: “John
//Doe ordered 5 T-shirt(s) on XYZ Clothing store”.
let visitorName = "<b> john deo </b>";
let productTitle = "<b> T-shirt(s) </b>";
let Quantity =5 ;
 
document.write(visitorName + "" + "orderd" + productTitle + "" + "on XYZ Clothing store")