//Question 1. Declare 3 variables in one statement.
//let name, age, city;

//Question 2. Declare 5 legal & 5 illegal variable names.
//legal
//var myName, $price, _value, user1, totalAmount;

// Illegal
// let 123name;
// let my-name;
// let var;
// let user name;
// let alert;





// Question 3. Display this in your browser

document.write("<h1>Rules for naming JS variables</h1>");
document.write("variable names can only contain <b>letters</b>, <b>numbers</b>, <b>$</b> and <b>_</b>. for example: <b>$my_1stvariable</b><br>");
document.write("variable must begin with a <b>letters</b>,<b>$</b> or <b>_</b>. for example: <b>$name</b>, <b_name></b> or <b>name</b><br>");
document.write("variable name are case <b>sensitive</b><br>");
document.write("variable names should not be JS <b>keywords</b>");